services:
  web:
    environment:
      - RAILS_ENV=development
    build: .
    ports:
      - "3000:3000"
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
    tty: true
    stdin_open: true